# Generated by Django 6.1.1 on 2026-10-08 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='close_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shift',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='denominations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ShiftReopen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_end_time', models.DateTimeField(blank=True, null=True)),
                ('previous_expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('previous_counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('previous_variance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('previous_denominations', models.JSONField(blank=True, null=True)),
                ('previous_close_reason', models.CharField(blank=True, max_length=200)),
                ('previous_closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_reopens', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reopens', to='shifts.shift')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
    ]
