# Generated by Django 6.1.1 on 2026-10-08 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_cashmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('report_no', models.CharField(max_length=20, unique=True)),
                ('closed_at', models.DateTimeField()),
                ('cashier_file', models.CharField(max_length=120)),
                ('owner_file', models.CharField(max_length=120)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='shifts.shift')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('shift', 'version'), name='one_report_per_version')],
            },
        ),
    ]
