# Generated by Django 6.1.1 on 2026-10-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_shiftreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreopen',
            name='previous_wallet_checks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
