# Generated by Django 6.1.1 on 2026-10-09 10:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0004_shiftreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rebate_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoadProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='wallets.loadnetwork')),
            ],
            options={
                'ordering': ['network__name', 'face_value', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('load', 'Mobile load'), ('ewallet', 'E-wallet')], max_length=10)),
                ('provider', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('low_level', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('type', 'provider'), name='one_wallet_per_provider')],
            },
        ),
        migrations.CreateModel(
            name='LoadTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rebate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_no', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=7)),
                ('receipt_no', models.CharField(max_length=20, unique=True)),
                ('failed_note', models.CharField(blank=True, max_length=200)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='load_transactions', to=settings.AUTH_USER_MODEL)),
                ('load_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.loadproduct')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='load_transactions', to='shifts.shift')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='load_transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('topup', 'Top-up'), ('load_sent', 'Load sent'), ('cash_in', 'Cash in'), ('cash_out', 'Cash out'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_no', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=12)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='shifts.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='loadproduct',
            constraint=models.UniqueConstraint(fields=('network', 'name'), name='one_load_product_name'),
        ),
        migrations.AddConstraint(
            model_name='loadtransaction',
            constraint=models.UniqueConstraint(fields=('network_name', 'reference_no'), name='one_reference_per_network'),
        ),
    ]
