# Generated by Django 6.1.1 on 2026-10-09 11:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_shiftreport'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('cash_in', 'Cash in'), ('cash_out', 'Cash out')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('table_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_overridden', models.BooleanField(default=False)),
                ('fee_override_reason', models.CharField(blank=True, max_length=200)),
                ('customer_mobile', models.CharField(max_length=20)),
                ('reference_no', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('reversed', 'Reversed')], default='success', max_length=8)),
                ('receipt_no', models.CharField(max_length=20, unique=True)),
                ('reversed_note', models.CharField(blank=True, max_length=200)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ewallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ewallet_transactions', to='shifts.shift')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ewallet_transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'constraints': [models.UniqueConstraint(fields=('wallet', 'reference_no'), name='one_reference_per_wallet')],
            },
        ),
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.PositiveIntegerField()),
                ('max_amount', models.PositiveIntegerField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_rules', to='wallets.wallet')),
            ],
            options={
                'ordering': ['wallet', 'min_amount'],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_amount__lte', models.F('max_amount'))), name='fee_range_valid')],
            },
        ),
    ]
