# Generated by Django 6.1.1 on 2026-10-10 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_shiftreopen_previous_wallet_checks'),
        ('wallets', '0002_ewallettransaction_feerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftWalletCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_start', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_start', models.DecimalField(decimal_places=2, max_digits=12)),
                ('difference_start', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_end', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_end', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('difference_end', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_checks', to='shifts.shift')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_checks', to='wallets.wallet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shift', 'wallet'), name='one_check_per_wallet_per_shift')],
            },
        ),
    ]
